site_name: next-cvat
repo_url: https://github.com/nextml/next-cvat
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [next_cvat]
          options:
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            docstring_style: google
            docstring_section_style: spacy
            show_root_members_full_path: true
            show_object_full_path: true
            show_root_full_path: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            heading_level: 1

nav:
  - Home: index.md
  - API Reference:
    - Client: api/client.md
    - Project: api/project.md
    - Task: api/task.md
    - Job: api/job.md
    - JobAnnotations: api/job_annotations.md
    - Frame: api/frame.md
    - Annotations: api/annotations.md
  - Examples:
    - Basic Usage: examples/basic_usage.md 