site_name: next-cvat
repo_url: https://github.com/nextml/next-cvat
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [next_cvat]
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: true
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            heading_level: 3
            show_submodules: false
            members_order: source
            group_by_category: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            show_module_members: false
            show_module: false
            show_bases: false
            show_signature: false
            show_signature_annotations: false
            members: []
            filters: ["!^_", "!^test_"]
            show_root_toc_entry: false
            show_root_heading_as_title: false
            show_root_members: false
            show_root_package_header: false

nav:
  - Getting Started:
    - Overview: index.md
    - Basic Usage: examples/basic_usage.md
  - API Documentation:
    - Client: api/client.md
    - Project: api/project.md
    - Task: api/task.md
    - Job: api/job.md
    - JobAnnotations: api/job_annotations.md
    - Frame: api/frame.md
    - Annotations: api/annotations.md
    - Types: api/types.md 